# Generated by Django 5.0.1 on 2024-01-23 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutlineKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_key', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='outlineuser',
            name='ip_address',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='outlineuser',
            name='outline_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outline_user', to='outline_users.outlinekey'),
        ),
        migrations.DeleteModel(
            name='OutlineKeys',
        ),
    ]
