# Generated by Django 5.0.1 on 2024-01-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline_users', '0002_outlinekey_outlineuser_ip_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlinekey',
            name='json_key',
        ),
        migrations.AddField(
            model_name='outlinekey',
            name='outline_key',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
