# Generated by Django 5.0.1 on 2024-01-30 06:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline_users', '0003_remove_outlinekey_json_key_outlinekey_outline_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlineuser',
            name='uniq_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entry', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(max_length=20)),
                ('outline_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outline_users.outlinekey')),
                ('outline_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outline_users.outlineuser')),
            ],
        ),
    ]
