services:
  web-app:
    build:
      context: .
    ports:
      - "8010:8010"
    volumes:
      - /src /src/data
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=dbpass
    command: >
      sh -c "python src/manage.py migrate && python src/manage.py runserver 0.0.0.0:8010"
    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass